# Generated by Django 3.0.5 on 2020-04-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='listed_projects',
            name='votes',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Votes',
        ),
    ]
